
- name: Install docker 
  hosts: "{{docker_node}}"
  vars_files:
    - "./vars"
  tasks:
    - name: Install docker
      apt:
        name: docker
        update_cache: yes
        state: present

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64
        dest: /usr/bin/docker-compose
        mode: +x

    - name: Add ubuntu to docker  
      user:
        name: eubutnu 
        groups: docker
      
    - meta: reset_connection

    - name: Start docker  
      service:
        name: docker
        state: started
